package database;

import database.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ACTION.
 */
public class Action {

    private Long id;
    private String name;
    private String imgUrl;
    private Integer orderNumber;
    private Long kidActivityId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient ActionDao myDao;

    private KidActivity kidActivity;
    private Long kidActivity__resolvedKey;


    public Action() {
    }

    public Action(Long id) {
        this.id = id;
    }

    public Action(Long id, String name, String imgUrl, Integer orderNumber, Long kidActivityId) {
        this.id = id;
        this.name = name;
        this.imgUrl = imgUrl;
        this.orderNumber = orderNumber;
        this.kidActivityId = kidActivityId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getActionDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public Integer getOrderNumber() {
        return orderNumber;
    }

    public void setOrderNumber(Integer orderNumber) {
        this.orderNumber = orderNumber;
    }

    public Long getKidActivityId() {
        return kidActivityId;
    }

    public void setKidActivityId(Long kidActivityId) {
        this.kidActivityId = kidActivityId;
    }

    /** To-one relationship, resolved on first access. */
    public KidActivity getKidActivity() {
        Long __key = this.kidActivityId;
        if (kidActivity__resolvedKey == null || !kidActivity__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            KidActivityDao targetDao = daoSession.getKidActivityDao();
            KidActivity kidActivityNew = targetDao.load(__key);
            synchronized (this) {
                kidActivity = kidActivityNew;
            	kidActivity__resolvedKey = __key;
            }
        }
        return kidActivity;
    }

    public void setKidActivity(KidActivity kidActivity) {
        synchronized (this) {
            this.kidActivity = kidActivity;
            kidActivityId = kidActivity == null ? null : kidActivity.getId();
            kidActivity__resolvedKey = kidActivityId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
